version: "3.7"

x-env-vars: &envs
  environment:
    DEBUG: "true"
    REDIS_HOST: "redis"
    REDIS_PORT: 6379
    REDIS_CODES_KEY: "codes"
    REDIS_CODES_THRESHOLD: 100
    MONGODB_HOST: "mongodb"
    MONGODB_PORT: 27017
    MONGO_INITDB_DATABASE: 'eancodes'
    MONGO_INITDB_ROOT_USERNAME: 'tornado'
    MONGO_INITDB_ROOT_PASSWORD: 'tornado'


services:
  gateway:
    <<: *envs
    build: gateway
    command: python app.py
    volumes:
      - ./gateway/app/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - redis
  eanworker:
    <<: *envs
    build: eanworker
    command: python worker.py
    volumes:
      - ./eanworker/app/:/app/
    depends_on:
      - redis
  locust:
    <<: *envs
    build: locust
    command: locust --host=http://gateway:8000
    volumes:
      - ./locust/app/:/app/
    ports:
      - "8089:8089"
    depends_on:
      - gateway
      - eanworker
      - redis
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  mongodb:
    <<: *envs
    image: mongo
  redis_exporter:
    image: oliver006/redis_exporter
    environment:
      REDIS_ADDR: "redis://redis:6379"
      REDIS_EXPORTER_CHECK_SINGLE_KEYS: "codes"
      REDIS_EXPORTER_INCL_SYSTEM_METRICS: 1
    ports:
      - "9121:9121"
  mongodb_exporter:
    image: eses/mongodb_exporter
    ports:
      - "9104:9104"
    environment:
      MONGODB_URI: "mongodb://tornado:tornado@mongodb:27017"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
