{
 "title": "GLOBAL",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "WORKER collision number omitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "collision_total" }
   ]
  },
  {
   "title": "MONGODB documents total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_document_total{instance=\"mongodb_exporter:9104\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "GATEWAY redis req time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "redis_request_latency_sum" }
   ]
  },
  {
   "title": "REDIS codes size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_key_size{key=\"codes\"}",
     "legendFormat": "codes"
    }
   ]
  },
  {
   "title": "GATEWAY total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "requests_total",
     "legendFormat": "{{endpoint}} - {{http_status}} - {{method}}"
    }
   ]
  },
  {
   "title": "MONGODB cursor open",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_cursor_open",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "MONGODB connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mongodb_mongod_connections", "legendFormat": "{{state}}" }
   ]
  }
 ]
}