# prometheus.yml
global:
    scrape_interval: 15s
    external_labels:
        monitor: 'my-monitor'
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['prometheus:9090']
    - job_name: 'redis_exporter'
      static_configs:
        - targets: ['redis_exporter:9121']
    - job_name: 'mongodb_exporter'
      static_configs:
        - targets: ['mongodb_exporter:9104']
    - job_name: 'gateway_exporter'
      static_configs:
        - targets: ['gateway:8000']